### ISSUE TITLE
Docker no longer working

### ISSUE THREAD

**Issue by kanytu** [henshin/filebuster#12]
An error is thrown every time I try to run the command:

docker run -ti --rm filebuster -u http://yoursite/{fuzz}.jsp

```
Can't locate Net/DNS.pm in @INC (you may need to install the Net::DNS module) (@INC contains: /usr/local/lib/perl5/site_perl/5.30.0/x86_64-linux-gnu-thread-multi /usr/local/lib/perl5/site_perl/5.30.0 /usr/local/lib/perl5/vendor_perl/5.30.0/x86_64-linux-gnu-thread-multi /usr/local/lib/perl5/vendor_perl/5.30.0 /usr/local/lib/perl5/5.30.0/x86_64-linux-gnu-thread-multi /usr/local/lib/perl5/5.30.0) at /filebuster/filebuster.pl line 28.
BEGIN failed--compilation aborted at /filebuster/filebuster.pl line 28.
```

**Comment by henshin** [comment]
Thanks for reporting this. One of the dependencies was missing. It's now fixed with commit https://github.com/henshin/filebuster/commit/cd14ff9b6408949a5e8558ac21272098d87686ec
Also added a suggestion to run the docker with the `--init` so that CTRL+C can stop the execution
