### ISSUE TITLE
Install errors -> Net::DNS::Lite module 

### ISSUE THREAD

**Issue by Os3r3um** [henshin/filebuster#4]
Hi there, 

Trying to play a little with this tool. However, the install process got me into the following situation regards with the Net::DNS::Lite module which I'm trying to install. I'm running anUbuntu Server 16.04.3 LTS,  Perl 5.22 version.

```
Running install for module 'Net::DNS::Lite'
Checksum for /home/the-preacher/.cpan/sources/authors/id/K/KA/KAZUHO/Net-DNS-Lite-0.12.tar.gz ok
Configuring K/KA/KAZUHO/Net-DNS-Lite-0.12.tar.gz with Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Net::DNS::Lite
Writing MYMETA.yml and MYMETA.json
  KAZUHO/Net-DNS-Lite-0.12.tar.gz
  /usr/bin/perl Makefile.PL INSTALLDIRS=site -- OK
Running make for K/KA/KAZUHO/Net-DNS-Lite-0.12.tar.gz
cp lib/Net/DNS/Lite.pm blib/lib/Net/DNS/Lite.pm
Manifying 1 pod document
  KAZUHO/Net-DNS-Lite-0.12.tar.gz
  /usr/bin/make -- OK
Running make test
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'inc', 'blib/lib', 'blib/arch')" t/*.t
t/00base.t ......... 3/? 
#   Failed test 'lookup google.com'
#   at t/00base.t line 18.
t/00base.t ......... 4/? 
#   Failed test 'lookup www (search = google.com)'
#   at t/00base.t line 24.
```

Any ideas about how to have this one error-free installed?

Cheers.

**Comment by henshin** [comment]
Hi @Os3r3um.
Try to skip CPAN tests. I will be changing the installation instructions soon regarding this because from my initial tests, skipping CPAN tests makes the installation process much faster and it doesn't seem needed.
Try this:
`cpan -T install YAML Furl Switch Benchmark Cache::LRU Net::DNS::Lite List::MoreUtils IO::Socket::SSL URI::Escape HTML::Entities IO::Socket::Socks::Wrapper`

**Comment by Os3r3um** [comment]
Just big thank you! You should mention it as a workaround with the tool README file :)

Thanks!
